name: The Pipe

on:
  push:

jobs:
  clang-format:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Run clang-format
      continue-on-error: true
      run: find src include tests -name "*.cpp" -o -name "*.h" | xargs clang-format --dry-run --Werror

  clang-tidy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Generate compile commands
      run: bash build.sh config

    - name: Run clang-tidy
      continue-on-error: true
      run: find src tests -name "*.cpp" | xargs -n1 -P "$(nproc)" clang-tidy -p build

  build-test:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build
      run: bash build.sh build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
