name: The Pipe

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build
      run: bash build.sh build

    - name: Run clang-format
      run: find src include tests -name "*.cpp" -o -name "*.h" | xargs clang-format-14 --dry-run --Werror

    - name: Run clang-tidy
      run: find src include tests -name '*.cpp' -o -name '*.h' | xargs clang-tidy-14 -p build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: sek
        path: build/src/sek
